# Generated by Django 2.0.1 on 2018-01-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='affiliation',
            new_name='has_access',
        ),
    ]
