# Generated by Django 2.1.3 on 2019-02-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_globalalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
