# Generated by Django 2.1.3 on 2019-02-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_notifications_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='threshold',
            field=models.BooleanField(default=False),
        ),
    ]
