# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='updates',
            field=models.ManyToManyField(default=None, to='petitions.Update'),
        ),
    ]
