# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_auto_20161103_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='response',
        ),
        migrations.AddField(
            model_name='petition',
            name='response',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='petitions.Response'),
        ),
    ]
