# Generated by Django 2.1.3 on 2019-02-14 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petitions', '0003_petition_old_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField()),
                ('reported_for', models.TextField(blank=True, default='')),
                ('petition_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='petitions.Petition')),
                ('reporter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
