# Generated by Django 2.1.3 on 2019-02-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0004_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='petition_id',
            new_name='petition',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reporter_id',
            new_name='reporter',
        ),
    ]
