# Generated by Django 2.1.11 on 2022-11-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0005_auto_20190215_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='committee',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
